name: Deploy Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0  # Specify the Terraform version you need

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan \
          -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
          -var "aws_secret_key=${{ secrets.AWS_SECRET_KEY }}" \
          -var-file=variables.tfvars

      - name: Upload Terraform Plan
        if: success()  # Only upload if the plan step succeeded
        uses: actions/upload-artifact@v3  # Use the latest version
        with:
          name: terraform-plan
          path: tfplan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan
